### ISSUE TITLE
Production experience?

### ISSUE THREAD

**Issue by aehlke** [namecare/app-store-server-library-rust#14]
Hi, I understand this is beta and subject to change, however I'd like to ask if you've run this in production and how your experience with it has been so far. Thanks

**Comment by tikhop** [comment]
Hi @aehlke, thanks for asking.

We are using it for our own [app](https://itunes.apple.com/app/id1578773551) to decode and verify App Store notifications. It works well for both sandbox and production servers.

**Comment by tikhop** [comment]
Hey @aehlke, just wanted to let you know, that I have released v0.5.0 that includes "Promo offer signature generator" feature and brings more tests and some documentation.

Eventually, I'm planing to implement the rest (API Client, Receipt Util and ocsp validation), but I can't provide any ETA now. Please, feel free to request a feature and don't hesitate to ask a question. 

I'm closing the ticket for now, thanks again for asking :)
