### ISSUE TITLE
verify and decode renewal_info error

### ISSUE THREAD

**Issue by xbitlabs** [namecare/app-store-server-library-rust#22]
Expect Payload: Error(Json(Error("expected value", line: 1, column: 118)))
stack backtrace:
   0: rust_begin_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/result.rs:1652:5
   3: core::result::Result<T,E>::expect
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/result.rs:1034:23
   4: app_store_server_library::signed_data_verifier::SignedDataVerifier::decode_signed_object
             at ./app-store-server-library/src/signed_data_verifier.rs:180:23
   5: app_store_server_library::signed_data_verifier::SignedDataVerifier::verify_and_decode_renewal_info
             at ./app-store-server-library/src/signed_data_verifier.rs:143:74

**Comment by tikhop** [comment]
Hi @xbitlabs, thanks for bringing this up. I will take a look shortly.
